name: Run Buy Rule 2 Scanner

on:
  schedule:
    - cron: "0 8 * * *"  # 每天 UTC 时间 08:00 运行（北京时间下午4点）
  workflow_dispatch:      # 手动运行按钮支持

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install yfinance pandas lxml

    - name: Run scanner
      run: python scanner.py

    - name: Commit result
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add result.txt
        git commit -m "Daily result update"
        git push
